name: Changelog

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Run a one-line script
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issues-label: "### Closed issues" 
          breaking-label: "### Breaking changes" 
          enhancement-label: "### Implemented enhancements" 
          bugs-label: "### Fixed bugs" 
          deprecated-label: "### Deprecated" 
          removed-label: "### Removed" 
          security-label: "### Security fixes"
          pullRequests: false
          author: false
          
      - name: "Print changelog to console"
        run: cat CHANGELOG.md
        
      - name: "Upload changelog"
        uses: actions/upload-artifact@v1.0.0
        with:
          name: "Changelog"
          path: CHANGELOG.md
