# This is a basic workflow to help you get started with Actions

name: Changelog

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    working-directory: osal
    
jobs:
  build:
    name: "Changelog Generation"
    runs-on: ubuntu-18.04
    steps:
      - name: "Check-out"
        uses: actions/checkout@v2
        
      - name: "Generate full changelog"
        id: generate-full-changelog
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issues: true
          issuesWoLabels: true
          pullRequests: true
          prWoLabels: true
          author: true
          unreleased: true
          compareLink: true
          stripGeneratorNotice: true
          verbose: true

      - name: "Print changelog to console"
        run: cat CHANGELOG.md
        
      - name: "Upload changelog"
        uses: actions/upload-artifact@v1.0.0
        with:
          name: "Changelog"
          path: CHANGELOG.md
