name: CI macOS

on: push

jobs:
  test:
    name: Test job
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: "Run CI task"
        run: |
          make test

      # TODO: The timer-add-api-test test is known to fail sometimes on GitHub Actions (both macOS and Linux, but macOS
      # is more often). The current hypothesis is that the timer cannot catch up when running on the (elastic) VMs.
      # Run tests more than once to increase the reproducibility.
      # Revert this change when the macOS branch is ready and create a separate ticket to track this for macOS and
      # Linux.
      - name: "Run flaky CI task #1"
        run: |
          make test_flaky

      - name: "Run flaky CI task #2"
        run: |
          make test_flaky

      - name: "Run flaky CI task #3"
        run: |
          make test_flaky

      - name: "Run flaky CI task #4"
        run: |
          make test_flaky

      - name: "Run flaky CI task #5"
        run: |
          make test_flaky

      - name: "Run flaky CI task #6"
        run: |
          make test_flaky

      - name: "Run flaky CI task #7"
        run: |
          make test_flaky

      - name: "Run flaky CI task #8"
        run: |
          make test_flaky

      - name: "Run flaky CI task #9"
        run: |
          make test_flaky

      - name: "Run flaky CI task #10"
        run: |
          make test_flaky
